### ISSUE TITLE
i need help if anyone ever runs into this

### ISSUE THREAD

**Issue by Judexyz** [Ciremun/freedom#210]
I got a problem which says like "debug assertion failed" can anyone help me if they're ever run into this problem?

<img width="554" height="405" alt="Image" src="https://github.com/user-attachments/assets/7a2cf779-00ae-465a-9be3-9a57a6908ee9" />

pls help me to fix this problem is it a problem from osu itself or msvc?

**Comment by corinve** [comment]
i think redownloading it and rebuilding should fix it

**Comment by Judexyz** [comment]
> i think redownloading it and rebuilding should fix it

im accepting my fate, i've redownloaded it and still doesn't work and idk how to fix it cuz when i go to the path shown (which is microsoft visual studio 2022 folder it's nothing and empty there)

and with the rebuilding problem, i don't really know how to do things cuz im not that good at programming stuff so rip me ig

**Comment by brazilianexperiments** [comment]
It could be a lot of things, but it might be related to the skins you're using in osu! (if you use any). Maybe try removing the skin entirely or even testing another version of osu! like stable or lazer. I don’t have much experience with this, but it’s worth a shot. Honestly, the most reliable solution might be to rebuild everything from scratch, even though it’s a bit of a hassle. Hope it works out!
